#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yoshihiro Ogishima
# SPDX-Licende-Identifier: BSD-3-Clause

import sys
import fileinput

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0

for line in fileinput.input():
    if line[0] == '*':
        line = line.lstrip('*')
        ans *= tonum(line)
    elif line[0] == '/':
        line = line.lstrip('/')
        ans /= tonum(line)
    else:
        ans += tonum(line)

print(ans)