#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yoshihiro Ogishima
# SPDX-Licende-Identifier: BSD-3-Clause

import sys

n = 0
ans = 0
strng = '_'

def tonum(s):
    global n
    n = 1
    try:
        return int(s)
    except:
        return float(s)

for line in sys.stdin:
    line = line.rstrip()
    if line == '###':
        if strng != '_': print(strng.lstrip('_'))
        if n == 1: print(ans)
        n = 0
        strng = '_'
        ans = 0
    elif line[0] == '>':    
        strng += line.lstrip('>')
    elif line[0] == '*':
        ans *= tonum(line.lstrip('*'))
    elif line[0] == '/':
        ans /= tonum(line.lstrip('/'))
    else:
        ans += tonum(line)

if strng != '_': print(strng.lstrip('_'))        
if n == 1: print(ans)